[package]
name = "ironmind"
version = "0.1.1"
edition = "2021"
authors = ["Jaden Arceneaux <contact@jadenarceneaux.com>"]
description = "A Brainf*ck built in Rust"
license = "MIT"
repository = "https://github.com/Jadens-arc/Iron-Mind"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
